### PR TITLE
fix: removed default timeout assignment when interval is present

### PR DESCRIPTION
**Pull request by naz**
closes https://github.com/breejs/bree/issues/50

This behavior makes job scheduling closer to how 
1. native [setInterval](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/setInterval) works 
> A function to be executed every delay milliseconds. 
2. [crontab](https://www.gnu.org/software/mcron/manual/html_node/Crontab-file.html) works
> Commands are executed by cron when the minute, hour, and month of year fields match the current time,

### CODE REVIEW

**Comment by niftylettuce** [comment]
I think if we accept this then we'll definitely have to document this in readme and update the examples.  Some people might think every three seconds including first second.

**Comment by naz** [comment]
@niftylettuce 100% agree. Will add documentation changes to this PR in a sec

**Comment by naz** [comment]
@niftylettuce pushed the docs change. 

While on topic. Was digging through the code had a code organization question I wanted to discuss. I think the `index.js` file is becoming quite big and might benefit if some of the methods were extracted into separate modules. For example, the `validateJob` method would could be extracted to a separate module e.g. `build-job` where single job initialization logic would live. And then it would allow to further break it down into proper validation and default assignment stages. Having separate module would also make it easier to test for specific defaults in isolation without building up whole bree class instance. Wdyt?

What's your vision of the repository/code structure? I wasn't sure if refactors like described above would fit/be welcome here.

**Comment by niftylettuce** [comment]
I'm open to another PR @naz

**Comment by niftylettuce** [comment]
v4.0.0 released, I've also made a npm deprecation notice for all prior versions since this is a pretty major breaking change

https://github.com/breejs/bree/releases/tag/v4.0.0

```sh
npm deprecate bree@"<4.0.0" "*IMPORTANT*: If you upgrade to Bree v4.0.0+, then you should note that if you want a job with an 'interval' option specified to also start on boot, you also need to now specify 'timeout: 0' as an option. See the updated docs at https://jobscheduler.net for more insight, or view the v4.0.0 release changelog at https://github.com/breejs/bree/releases/tag/v4.0.0 - thanks and happy hacking! - @niftylettuce"
```

**Pull request merged**
