### PR TITLE
feat: implement typescript support

### PR DESCRIPTION
**Pull request by colus001**
Implementing typescript. Some part I don't understand remains as `any` but most part especially instance and job config has been implemented. Probably issues still exist in detail. If you don't like this PR I can create another PR only includes index.d.ts too.

### CODE REVIEW

**Comment by niftylettuce** [comment]
I could only agree to merge this is you would agree to become a dedicated open source maintainer of this (and the TypeScript bindings).

**Comment by falkenhawk** [comment]
If that's the case, it'd be probably better off with pushing the typings to DefinitelyTyped imo

**Comment by gtolarc** [comment]
Can you guys merge this well? plz!

**Comment by niftylettuce** [comment]
I don't support Typescript, it requires contributors to have to learn yet another language, and it is not native pure vanilla JS.  It's also not native to Node either.  It's bad practice in the community and its bad for open source.

**Comment by gtolarc** [comment]
I thought it wouldn't be that difficult to maintain a type because there is only one export Bree.
But, I respect your opinion @niftylettuce

**Comment by niftylettuce** [comment]
Thank you, it's just that once I would accept this here, then everyone would want it on all my other projects and work, which would be way too insane to manage, as it is already way too insanely hard to keep up with everything.  I really appreciate your kind words, usually I get someone cursing at me in return for telling them I can't do this because it's too much.

**Comment by colus001** [comment]
I didn't know there's comment on this PR. I was willing to become a maintainer since I planned to use this for my own project. By the way I found out that this is not enough to run typescript since Bree use worker thread and it requires more jobs to run it with something like ts-node especially for dev env. It will require SOME structure to use smoothly in actual typescript project.

Now I'm using agenda and still not 100% content with it. Still believe this is good way to handle cron jobs and maybe next time I'll bring something reliable for other compiled language.

**Comment by niftylettuce** [comment]
As a previous maintainer of Agenda I'd strongly recommend you to switch to Bree, or perhaps contribute to DefinitelyTyped to add bindings or whatever for TS for bree.  The headaches Agenda will bring you in the horrible will be very bad...

**Comment by colus001** [comment]
I'll definitely do. We already have memory issue for long running cron job even without agenda. 🤣 Don't want even more. Let me try to find out how to run smoothly Bree with ts and will get back to you. Thanks for the great library though!

**Comment by niftylettuce** [comment]
Could you make a PR to https://github.com/DefinitelyTyped/DefinitelyTyped and then just make a PR to this repo with instructions for how to use it with TS or something?

**Comment by gtolarc** [comment]
The worker threads technology itself comes out to write a js file as a worker, but if you want to use ts to implement a worker, isn't it something the user should do?
I don't know if this project should support it on its own. There are already known user-level methods.
Just adding to DefinitelyTyped would be great! @colus001 @niftylettuce

**Pull request closed without merging**
